service: nonomura-sls-fastapi

custom:
  author: ${opt:author, "nonomura"}
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-northeast-1"}
  pythonRequirements:
    # invalidateCaches: true # キャッシュ
    noDeploy:
      - pytest

provider:
  name: aws
  runtime: python3.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  # environment:
  #   LOG_LEVEL: ${env:LOG_LEVEL}
  versionFunctions: false
  # deploymentBucket:
  #   name: '${self:custom.deploymentBucketName}'
  logRetentionInDays: 3 # Cloudwatchのログ保存期間日数

plugins:
  - serverless-python-requirements

functions:
  api:
    name: ${self:custom.author}-api-${self:custom.stage}
    handler: main.handler # mangumの位置を指定
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - schedule: 
          rate: rate(5 minutes) # 定期実行（コールド対策） 
          input: # health check
            resource: "/{proxy+}"
            path: "/health"
            httpMethod: "GET"
            requestContext: {}